# Generated by Django 4.2.25 on 2025-10-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesubmission',
            old_name='languages',
            new_name='language',
        ),
    ]
